### PR TITLE
Protect against malicious blob names in Local File System Storage

### PR DESCRIPTION
**Pull request by Kukks**
Email me at evilkukka@gmail.com for more info

### CODE REVIEW

**Comment by jarroda** [comment]
This looks great.  Thanks!

**Comment by Kukks** [comment]
No problem, will you do a release soon since this is a bit of vulnerability?

**Comment by ericgreenmix** [comment]
Just pushed to as 2.11.1. Should be indexed by nuget shortly

**Comment by Kukks** [comment]
Awesome, thanks!

**Comment by NicolasDorier** [comment]
IMHO, this fix is a hack. The proper way to fix it is to use `Path.Combine` and then verify on the full path that the path start with `_basePath`

**Comment by NicolasDorier** [comment]
Sorry, talked with Kukks and the check is correctly done. Though the regex is useless and wrong. (matching the first char which is ASCII)

**Comment by ericgreenmix** [comment]
@NicolasDorier Feel free to submit a cleanup or better solution. Thanks

**Comment by ericgreenmix** [comment]
@NicolasDorier and @Kukks a new version 2.11.2 is on its way to Nuget that removes the Regex check, because you are right, it is not needed.

**Pull request merged**
