### PR TITLE
Added profile credentials and encryption mode for AWS S3

### PR DESCRIPTION
**Pull request by imperugo**
Hi, 
I've added the opportunity to use the AWS profile instead of the API Key and Secret for the connection (is an option, there aren't breaking changes for that) and also the opportunity to specify the encryption method for the object requests

### CODE REVIEW

**Comment by jarroda** [comment]
@imperugo Thanks for this.  Could you please sign the CLA? https://www.clahub.com/agreements/2020IP/TwentyTwenty.Storage

After signing that, I can merge your changes.

**Comment by imperugo** [comment]
Done

**Comment by jarroda** [comment]
Thanks.  Merged.

**Comment by imperugo** [comment]
Cool
let me know when is o nuget

**Comment by imperugo** [comment]
Any news?

**Comment by jarroda** [comment]
`2.6.1` is now on Nuget and contains these changes.

**Comment by imperugo** [comment]
thx

**Pull request merged**
