### PR TITLE
Allow specifying the timeout of the Amazon provider.

### PR DESCRIPTION
**Pull request by jbinder**
Hi, it would be nice to be able to specify the timeout of the Amazon provider.

### CODE REVIEW

**Comment by jarroda** [comment]
Hey thanks for the contribution.  Would you please sign the CLA https://www.clahub.com/agreements/2020IP/TwentyTwenty.Storage and we'll get this merged in.  Thanks.

**Comment by jbinder** [comment]
@jarroda Done, thanks!

**Comment by jarroda** [comment]
This change is in version 2.7.0, which is now on nuget.

**Comment by jbinder** [comment]
Great! Thank you!

**Pull request merged**
